#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 28 16:09:32 2024
Use F bank as nn.Module for feature extraction layer
@author: amir.m
"""
import torch.nn as nn
from nnAudio import features
import torchaudio 
import pdb

class Fbank(nn.Module):
    def __init__(self, num_mel_bins=128, sample_frequency=16000, frame_shift=10, 
                 frame_length=25):
        super(Fbank, self).__init__()
        
        
        self.num_mel_bins = num_mel_bins
        self.sample_frequency = sample_frequency
        self.frame_shift = frame_shift
        self.frame_length = frame_length
        
        self.spec_norm = True
      

        
    def forward(self, x):
       
        #Extract audio feature 
        x_f = torchaudio.compliance.kaldi.fbank(x, num_mel_bins=self.num_mel_bins, 
                                                sample_frequency=self.sample_frequency, 
                                                frame_shift=self.frame_shift, 
                                                frame_length=self.frame_length)
    
        x_f = x_f.unsqueeze(1)
        return x

